a = input(f'Digite algo: ')
print(type(a))
print(f'Só tem espaços? ', a.isspace())
print(f'É um número? ', a.isalnum())
print(f'É alfabético? ', a.isalpha())
print(f'É alfanúmérico? ', a.isalnum())
print(f'É minúsculo? ', a.islower())
print(f'É maiúsculo? ', a.isupper())
print(f'Esta capitalizada? ', a.istitle())